services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_db
    command: ["postgres", "-p", "5342"]
    ports:
      - "5433:5342"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U test -d test_db -p 5342"]
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data

volumes:
  dev-postgres-data:
# docker compose -f docker-compose.dev.yaml up -d db
