services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    command: ["postgres", "-p", "5342"]
    ports:
      - "5433:5342"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U test -d test_db -p 5342"]
      interval: 2s
      timeout: 2s
      retries: 30
# docker compose -f docker-compose.test.yaml up -d db
